// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CIDXMINIMAL_CIDX_MIN_H_
#define FLATBUFFERS_GENERATED_CIDXMINIMAL_CIDX_MIN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace cidx {
namespace min {

struct Header;
struct HeaderBuilder;

struct Loc;

struct Symbol;

struct Edge;

struct Artifact;
struct ArtifactBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Loc FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t file_ref_;
  uint32_t line_;
  uint32_t col_;

 public:
  Loc()
      : file_ref_(0),
        line_(0),
        col_(0) {
  }
  Loc(uint32_t _file_ref, uint32_t _line, uint32_t _col)
      : file_ref_(::flatbuffers::EndianScalar(_file_ref)),
        line_(::flatbuffers::EndianScalar(_line)),
        col_(::flatbuffers::EndianScalar(_col)) {
  }
  uint32_t file_ref() const {
    return ::flatbuffers::EndianScalar(file_ref_);
  }
  uint32_t line() const {
    return ::flatbuffers::EndianScalar(line_);
  }
  uint32_t col() const {
    return ::flatbuffers::EndianScalar(col_);
  }
};
FLATBUFFERS_STRUCT_END(Loc, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Symbol FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t name_ref_;
  uint32_t usr_ref_;
  uint32_t parent_ref_;
  uint16_t kind_;
  uint16_t flags_;
  cidx::min::Loc loc_;

 public:
  Symbol()
      : name_ref_(0),
        usr_ref_(0),
        parent_ref_(0),
        kind_(0),
        flags_(0),
        loc_() {
  }
  Symbol(uint32_t _name_ref, uint32_t _usr_ref, uint32_t _parent_ref, uint16_t _kind, uint16_t _flags, const cidx::min::Loc &_loc)
      : name_ref_(::flatbuffers::EndianScalar(_name_ref)),
        usr_ref_(::flatbuffers::EndianScalar(_usr_ref)),
        parent_ref_(::flatbuffers::EndianScalar(_parent_ref)),
        kind_(::flatbuffers::EndianScalar(_kind)),
        flags_(::flatbuffers::EndianScalar(_flags)),
        loc_(_loc) {
  }
  uint32_t name_ref() const {
    return ::flatbuffers::EndianScalar(name_ref_);
  }
  uint32_t usr_ref() const {
    return ::flatbuffers::EndianScalar(usr_ref_);
  }
  uint32_t parent_ref() const {
    return ::flatbuffers::EndianScalar(parent_ref_);
  }
  uint16_t kind() const {
    return ::flatbuffers::EndianScalar(kind_);
  }
  uint16_t flags() const {
    return ::flatbuffers::EndianScalar(flags_);
  }
  const cidx::min::Loc &loc() const {
    return loc_;
  }
};
FLATBUFFERS_STRUCT_END(Symbol, 28);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Edge FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t src_local_;
  uint32_t dst_local_;
  uint8_t kind_;
  uint8_t extra_;
  int16_t padding0__;

 public:
  Edge()
      : src_local_(0),
        dst_local_(0),
        kind_(0),
        extra_(0),
        padding0__(0) {
    (void)padding0__;
  }
  Edge(uint32_t _src_local, uint32_t _dst_local, uint8_t _kind, uint8_t _extra)
      : src_local_(::flatbuffers::EndianScalar(_src_local)),
        dst_local_(::flatbuffers::EndianScalar(_dst_local)),
        kind_(::flatbuffers::EndianScalar(_kind)),
        extra_(::flatbuffers::EndianScalar(_extra)),
        padding0__(0) {
    (void)padding0__;
  }
  uint32_t src_local() const {
    return ::flatbuffers::EndianScalar(src_local_);
  }
  uint32_t dst_local() const {
    return ::flatbuffers::EndianScalar(dst_local_);
  }
  uint8_t kind() const {
    return ::flatbuffers::EndianScalar(kind_);
  }
  uint8_t extra() const {
    return ::flatbuffers::EndianScalar(extra_);
  }
};
FLATBUFFERS_STRUCT_END(Edge, 12);

struct Header FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ARTIFACT_VERSION = 4,
    VT_TU_FILE_ID = 6
  };
  uint16_t artifact_version() const {
    return GetField<uint16_t>(VT_ARTIFACT_VERSION, 0);
  }
  uint32_t tu_file_id() const {
    return GetField<uint32_t>(VT_TU_FILE_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_ARTIFACT_VERSION, 2) &&
           VerifyField<uint32_t>(verifier, VT_TU_FILE_ID, 4) &&
           verifier.EndTable();
  }
};

struct HeaderBuilder {
  typedef Header Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_artifact_version(uint16_t artifact_version) {
    fbb_.AddElement<uint16_t>(Header::VT_ARTIFACT_VERSION, artifact_version, 0);
  }
  void add_tu_file_id(uint32_t tu_file_id) {
    fbb_.AddElement<uint32_t>(Header::VT_TU_FILE_ID, tu_file_id, 0);
  }
  explicit HeaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Header> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Header>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Header> CreateHeader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t artifact_version = 0,
    uint32_t tu_file_id = 0) {
  HeaderBuilder builder_(_fbb);
  builder_.add_tu_file_id(tu_file_id);
  builder_.add_artifact_version(artifact_version);
  return builder_.Finish();
}

struct Artifact FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ArtifactBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_STRING_POOL = 6,
    VT_SYMBOLS = 8,
    VT_EDGES = 10,
    VT_INCLUDES = 12
  };
  const cidx::min::Header *header() const {
    return GetPointer<const cidx::min::Header *>(VT_HEADER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *string_pool() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_STRING_POOL);
  }
  const ::flatbuffers::Vector<const cidx::min::Symbol *> *symbols() const {
    return GetPointer<const ::flatbuffers::Vector<const cidx::min::Symbol *> *>(VT_SYMBOLS);
  }
  const ::flatbuffers::Vector<const cidx::min::Edge *> *edges() const {
    return GetPointer<const ::flatbuffers::Vector<const cidx::min::Edge *> *>(VT_EDGES);
  }
  const ::flatbuffers::Vector<uint32_t> *includes() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INCLUDES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HEADER) &&
           verifier.VerifyTable(header()) &&
           VerifyOffset(verifier, VT_STRING_POOL) &&
           verifier.VerifyVector(string_pool()) &&
           verifier.VerifyVectorOfStrings(string_pool()) &&
           VerifyOffset(verifier, VT_SYMBOLS) &&
           verifier.VerifyVector(symbols()) &&
           VerifyOffset(verifier, VT_EDGES) &&
           verifier.VerifyVector(edges()) &&
           VerifyOffset(verifier, VT_INCLUDES) &&
           verifier.VerifyVector(includes()) &&
           verifier.EndTable();
  }
};

struct ArtifactBuilder {
  typedef Artifact Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_header(::flatbuffers::Offset<cidx::min::Header> header) {
    fbb_.AddOffset(Artifact::VT_HEADER, header);
  }
  void add_string_pool(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> string_pool) {
    fbb_.AddOffset(Artifact::VT_STRING_POOL, string_pool);
  }
  void add_symbols(::flatbuffers::Offset<::flatbuffers::Vector<const cidx::min::Symbol *>> symbols) {
    fbb_.AddOffset(Artifact::VT_SYMBOLS, symbols);
  }
  void add_edges(::flatbuffers::Offset<::flatbuffers::Vector<const cidx::min::Edge *>> edges) {
    fbb_.AddOffset(Artifact::VT_EDGES, edges);
  }
  void add_includes(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> includes) {
    fbb_.AddOffset(Artifact::VT_INCLUDES, includes);
  }
  explicit ArtifactBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Artifact> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Artifact>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Artifact> CreateArtifact(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<cidx::min::Header> header = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> string_pool = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const cidx::min::Symbol *>> symbols = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const cidx::min::Edge *>> edges = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> includes = 0) {
  ArtifactBuilder builder_(_fbb);
  builder_.add_includes(includes);
  builder_.add_edges(edges);
  builder_.add_symbols(symbols);
  builder_.add_string_pool(string_pool);
  builder_.add_header(header);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Artifact> CreateArtifactDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<cidx::min::Header> header = 0,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *string_pool = nullptr,
    const std::vector<cidx::min::Symbol> *symbols = nullptr,
    const std::vector<cidx::min::Edge> *edges = nullptr,
    const std::vector<uint32_t> *includes = nullptr) {
  auto string_pool__ = string_pool ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*string_pool) : 0;
  auto symbols__ = symbols ? _fbb.CreateVectorOfStructs<cidx::min::Symbol>(*symbols) : 0;
  auto edges__ = edges ? _fbb.CreateVectorOfStructs<cidx::min::Edge>(*edges) : 0;
  auto includes__ = includes ? _fbb.CreateVector<uint32_t>(*includes) : 0;
  return cidx::min::CreateArtifact(
      _fbb,
      header,
      string_pool__,
      symbols__,
      edges__,
      includes__);
}

inline const cidx::min::Artifact *GetArtifact(const void *buf) {
  return ::flatbuffers::GetRoot<cidx::min::Artifact>(buf);
}

inline const cidx::min::Artifact *GetSizePrefixedArtifact(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<cidx::min::Artifact>(buf);
}

template <bool B = false>
inline bool VerifyArtifactBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<cidx::min::Artifact>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedArtifactBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<cidx::min::Artifact>(nullptr);
}

inline void FinishArtifactBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<cidx::min::Artifact> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedArtifactBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<cidx::min::Artifact> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace min
}  // namespace cidx

#endif  // FLATBUFFERS_GENERATED_CIDXMINIMAL_CIDX_MIN_H_
