#!/usr/bin/env python3
"""gen_kind_names.py — regenerate src/cli/kind_names.cpp from clang.cindex.

Run from the cidx-cpp repo root:
    python scripts/gen_kind_names.py

The output is a switch-case table that maps CXCursorKind int values to the
Python CursorKind.name strings.  The file header documents known irregularities
in the name table that no mechanical transform can reproduce (e.g. 121 →
"StmtExpr", 251 → "OMP_PARALLELFORSIMD_DIRECTIVE").

Usage:
    python scripts/gen_kind_names.py [--output PATH]
      --output PATH  write to PATH instead of src/cli/kind_names.cpp
"""
import argparse
import sys
from pathlib import Path


def _collect_kinds():
    """Return a sorted list of (int_value, name_str) from clang.cindex."""
    try:
        import clang.cindex as cx
    except ImportError:
        sys.exit("error: 'clang' package not found — run: pip install libclang")

    kinds = []
    for attr in dir(cx.CursorKind):
        val = getattr(cx.CursorKind, attr)
        if not isinstance(val, cx.CursorKind):
            continue
        # Use .name — the Python canonical identifier (may differ from
        # clang_getCursorKindSpelling in known irregular cases).
        kinds.append((int(val.value), val.name))
    kinds.sort()
    return kinds


def _generate(kinds) -> str:
    header = """\
// kind_names.cpp -- generated by scripts/gen_kind_names.py
// Maps CXCursorKind int values to the Python CursorKind.name strings.
// DO NOT EDIT BY HAND -- regenerate with: python scripts/gen_kind_names.py
//
// Irregularities (verified against clang.cindex 18.1.1):
//   121 -> StmtExpr  (not STMT_EXPR)
//   251 -> OMP_PARALLELFORSIMD_DIRECTIVE
//   264 -> OMP_TARGET_PARALLELFOR_DIRECTIVE
#include "cli/kind_names.hpp"

namespace cidx {
namespace cli {

const char *kind_name(unsigned kind) {
  switch (kind) {
"""
    cases = []
    for val, name in kinds:
        cases.append(f"  case {val}: return \"{name}\";\n")
    footer = """\
  default: {
    // Return a loud marker rather than silently diverging from Python.
    static thread_local char buf[32];
    std::snprintf(buf, sizeof(buf), "<UNKNOWN_KIND_%u>", kind);
    return buf;
  }
  }
}

} // namespace cli
} // namespace cidx
"""
    return header + "".join(cases) + footer


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--output", default="src/cli/kind_names.cpp",
                    help="output file (default: src/cli/kind_names.cpp)")
    args = ap.parse_args()

    kinds = _collect_kinds()
    content = _generate(kinds)
    out = Path(args.output)
    out.write_text(content, encoding="utf-8")
    print(f"wrote {len(kinds)} kinds to {out}")


if __name__ == "__main__":
    main()
