// kind_names.cpp -- generated by scripts/gen_kind_names.py
// Maps CXCursorKind int values to the Python CursorKind.name strings.
// DO NOT EDIT BY HAND -- regenerate with: python scripts/gen_kind_names.py
//
// Irregularities (verified against clang.cindex 18.1.1):
//   121 -> StmtExpr (not STMT_EXPR)
//   251 -> OMP_PARALLELFORSIMD_DIRECTIVE (not OMP_PARALLEL_FOR_SIMD_DIRECTIVE)
//   264 -> OMP_TARGET_PARALLELFOR_DIRECTIVE (not OMP_TARGET_PARALLEL_FOR_DIRECTIVE)
#include "cli/kind_names.hpp"

#include <cstdio>

namespace cidx {
namespace cli {

const char *kind_name(unsigned kind) {
  // Doctest-pinned spot-checks:
  //   8  -> FUNCTION_DECL   10 -> PARM_DECL     202 -> COMPOUND_STMT
  //   203 -> CASE_STMT      214 -> RETURN_STMT   121 -> StmtExpr
  switch (kind) {
  case 1: return "UNEXPOSED_DECL";
  case 2: return "STRUCT_DECL";
  case 3: return "UNION_DECL";
  case 4: return "CLASS_DECL";
  case 5: return "ENUM_DECL";
  case 6: return "FIELD_DECL";
  case 7: return "ENUM_CONSTANT_DECL";
  case 8: return "FUNCTION_DECL";
  case 9: return "VAR_DECL";
  case 10: return "PARM_DECL";
  case 11: return "OBJC_INTERFACE_DECL";
  case 12: return "OBJC_CATEGORY_DECL";
  case 13: return "OBJC_PROTOCOL_DECL";
  case 14: return "OBJC_PROPERTY_DECL";
  case 15: return "OBJC_IVAR_DECL";
  case 16: return "OBJC_INSTANCE_METHOD_DECL";
  case 17: return "OBJC_CLASS_METHOD_DECL";
  case 18: return "OBJC_IMPLEMENTATION_DECL";
  case 19: return "OBJC_CATEGORY_IMPL_DECL";
  case 20: return "TYPEDEF_DECL";
  case 21: return "CXX_METHOD";
  case 22: return "NAMESPACE";
  case 23: return "LINKAGE_SPEC";
  case 24: return "CONSTRUCTOR";
  case 25: return "DESTRUCTOR";
  case 26: return "CONVERSION_FUNCTION";
  case 27: return "TEMPLATE_TYPE_PARAMETER";
  case 28: return "TEMPLATE_NON_TYPE_PARAMETER";
  case 29: return "TEMPLATE_TEMPLATE_PARAMETER";
  case 30: return "FUNCTION_TEMPLATE";
  case 31: return "CLASS_TEMPLATE";
  case 32: return "CLASS_TEMPLATE_PARTIAL_SPECIALIZATION";
  case 33: return "NAMESPACE_ALIAS";
  case 34: return "USING_DIRECTIVE";
  case 35: return "USING_DECLARATION";
  case 36: return "TYPE_ALIAS_DECL";
  case 37: return "OBJC_SYNTHESIZE_DECL";
  case 38: return "OBJC_DYNAMIC_DECL";
  case 39: return "CXX_ACCESS_SPEC_DECL";
  case 40: return "OBJC_SUPER_CLASS_REF";
  case 41: return "OBJC_PROTOCOL_REF";
  case 42: return "OBJC_CLASS_REF";
  case 43: return "TYPE_REF";
  case 44: return "CXX_BASE_SPECIFIER";
  case 45: return "TEMPLATE_REF";
  case 46: return "NAMESPACE_REF";
  case 47: return "MEMBER_REF";
  case 48: return "LABEL_REF";
  case 49: return "OVERLOADED_DECL_REF";
  case 50: return "VARIABLE_REF";
  case 70: return "INVALID_FILE";
  case 71: return "NO_DECL_FOUND";
  case 72: return "NOT_IMPLEMENTED";
  case 73: return "INVALID_CODE";
  case 100: return "UNEXPOSED_EXPR";
  case 101: return "DECL_REF_EXPR";
  case 102: return "MEMBER_REF_EXPR";
  case 103: return "CALL_EXPR";
  case 104: return "OBJC_MESSAGE_EXPR";
  case 105: return "BLOCK_EXPR";
  case 106: return "INTEGER_LITERAL";
  case 107: return "FLOATING_LITERAL";
  case 108: return "IMAGINARY_LITERAL";
  case 109: return "STRING_LITERAL";
  case 110: return "CHARACTER_LITERAL";
  case 111: return "PAREN_EXPR";
  case 112: return "UNARY_OPERATOR";
  case 113: return "ARRAY_SUBSCRIPT_EXPR";
  case 114: return "BINARY_OPERATOR";
  case 115: return "COMPOUND_ASSIGNMENT_OPERATOR";
  case 116: return "CONDITIONAL_OPERATOR";
  case 117: return "CSTYLE_CAST_EXPR";
  case 118: return "COMPOUND_LITERAL_EXPR";
  case 119: return "INIT_LIST_EXPR";
  case 120: return "ADDR_LABEL_EXPR";
  case 121: return "StmtExpr";
  case 122: return "GENERIC_SELECTION_EXPR";
  case 123: return "GNU_NULL_EXPR";
  case 124: return "CXX_STATIC_CAST_EXPR";
  case 125: return "CXX_DYNAMIC_CAST_EXPR";
  case 126: return "CXX_REINTERPRET_CAST_EXPR";
  case 127: return "CXX_CONST_CAST_EXPR";
  case 128: return "CXX_FUNCTIONAL_CAST_EXPR";
  case 129: return "CXX_TYPEID_EXPR";
  case 130: return "CXX_BOOL_LITERAL_EXPR";
  case 131: return "CXX_NULL_PTR_LITERAL_EXPR";
  case 132: return "CXX_THIS_EXPR";
  case 133: return "CXX_THROW_EXPR";
  case 134: return "CXX_NEW_EXPR";
  case 135: return "CXX_DELETE_EXPR";
  case 136: return "CXX_UNARY_EXPR";
  case 137: return "OBJC_STRING_LITERAL";
  case 138: return "OBJC_ENCODE_EXPR";
  case 139: return "OBJC_SELECTOR_EXPR";
  case 140: return "OBJC_PROTOCOL_EXPR";
  case 141: return "OBJC_BRIDGE_CAST_EXPR";
  case 142: return "PACK_EXPANSION_EXPR";
  case 143: return "SIZE_OF_PACK_EXPR";
  case 144: return "LAMBDA_EXPR";
  case 145: return "OBJ_BOOL_LITERAL_EXPR";
  case 146: return "OBJ_SELF_EXPR";
  case 147: return "OMP_ARRAY_SECTION_EXPR";
  case 148: return "OBJC_AVAILABILITY_CHECK_EXPR";
  case 149: return "FIXED_POINT_LITERAL";
  case 150: return "OMP_ARRAY_SHAPING_EXPR";
  case 151: return "OMP_ITERATOR_EXPR";
  case 152: return "CXX_ADDRSPACE_CAST_EXPR";
  case 153: return "CONCEPT_SPECIALIZATION_EXPR";
  case 154: return "REQUIRES_EXPR";
  case 200: return "UNEXPOSED_STMT";
  case 201: return "LABEL_STMT";
  case 202: return "COMPOUND_STMT";
  case 203: return "CASE_STMT";
  case 204: return "DEFAULT_STMT";
  case 205: return "IF_STMT";
  case 206: return "SWITCH_STMT";
  case 207: return "WHILE_STMT";
  case 208: return "DO_STMT";
  case 209: return "FOR_STMT";
  case 210: return "GOTO_STMT";
  case 211: return "INDIRECT_GOTO_STMT";
  case 212: return "CONTINUE_STMT";
  case 213: return "BREAK_STMT";
  case 214: return "RETURN_STMT";
  case 215: return "ASM_STMT";
  case 216: return "OBJC_AT_TRY_STMT";
  case 217: return "OBJC_AT_CATCH_STMT";
  case 218: return "OBJC_AT_FINALLY_STMT";
  case 219: return "OBJC_AT_THROW_STMT";
  case 220: return "OBJC_AT_SYNCHRONIZED_STMT";
  case 221: return "OBJC_AUTORELEASE_POOL_STMT";
  case 222: return "OBJC_FOR_COLLECTION_STMT";
  case 223: return "CXX_CATCH_STMT";
  case 224: return "CXX_TRY_STMT";
  case 225: return "CXX_FOR_RANGE_STMT";
  case 226: return "SEH_TRY_STMT";
  case 227: return "SEH_EXCEPT_STMT";
  case 228: return "SEH_FINALLY_STMT";
  case 229: return "MS_ASM_STMT";
  case 230: return "NULL_STMT";
  case 231: return "DECL_STMT";
  case 232: return "OMP_PARALLEL_DIRECTIVE";
  case 233: return "OMP_SIMD_DIRECTIVE";
  case 234: return "OMP_FOR_DIRECTIVE";
  case 235: return "OMP_SECTIONS_DIRECTIVE";
  case 236: return "OMP_SECTION_DIRECTIVE";
  case 237: return "OMP_SINGLE_DIRECTIVE";
  case 238: return "OMP_PARALLEL_FOR_DIRECTIVE";
  case 239: return "OMP_PARALLEL_SECTIONS_DIRECTIVE";
  case 240: return "OMP_TASK_DIRECTIVE";
  case 241: return "OMP_MASTER_DIRECTIVE";
  case 242: return "OMP_CRITICAL_DIRECTIVE";
  case 243: return "OMP_TASKYIELD_DIRECTIVE";
  case 244: return "OMP_BARRIER_DIRECTIVE";
  case 245: return "OMP_TASKWAIT_DIRECTIVE";
  case 246: return "OMP_FLUSH_DIRECTIVE";
  case 247: return "SEH_LEAVE_STMT";
  case 248: return "OMP_ORDERED_DIRECTIVE";
  case 249: return "OMP_ATOMIC_DIRECTIVE";
  case 250: return "OMP_FOR_SIMD_DIRECTIVE";
  case 251: return "OMP_PARALLELFORSIMD_DIRECTIVE";
  case 252: return "OMP_TARGET_DIRECTIVE";
  case 253: return "OMP_TEAMS_DIRECTIVE";
  case 254: return "OMP_TASKGROUP_DIRECTIVE";
  case 255: return "OMP_CANCELLATION_POINT_DIRECTIVE";
  case 256: return "OMP_CANCEL_DIRECTIVE";
  case 257: return "OMP_TARGET_DATA_DIRECTIVE";
  case 258: return "OMP_TASK_LOOP_DIRECTIVE";
  case 259: return "OMP_TASK_LOOP_SIMD_DIRECTIVE";
  case 260: return "OMP_DISTRIBUTE_DIRECTIVE";
  case 261: return "OMP_TARGET_ENTER_DATA_DIRECTIVE";
  case 262: return "OMP_TARGET_EXIT_DATA_DIRECTIVE";
  case 263: return "OMP_TARGET_PARALLEL_DIRECTIVE";
  case 264: return "OMP_TARGET_PARALLELFOR_DIRECTIVE";
  case 265: return "OMP_TARGET_UPDATE_DIRECTIVE";
  case 266: return "OMP_DISTRIBUTE_PARALLELFOR_DIRECTIVE";
  case 267: return "OMP_DISTRIBUTE_PARALLEL_FOR_SIMD_DIRECTIVE";
  case 268: return "OMP_DISTRIBUTE_SIMD_DIRECTIVE";
  case 269: return "OMP_TARGET_PARALLEL_FOR_SIMD_DIRECTIVE";
  case 270: return "OMP_TARGET_SIMD_DIRECTIVE";
  case 271: return "OMP_TEAMS_DISTRIBUTE_DIRECTIVE";
  case 272: return "OMP_TEAMS_DISTRIBUTE_SIMD_DIRECTIVE";
  case 273: return "OMP_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD_DIRECTIVE";
  case 274: return "OMP_TEAMS_DISTRIBUTE_PARALLEL_FOR_DIRECTIVE";
  case 275: return "OMP_TARGET_TEAMS_DIRECTIVE";
  case 276: return "OMP_TARGET_TEAMS_DISTRIBUTE_DIRECTIVE";
  case 277: return "OMP_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR_DIRECTIVE";
  case 278: return "OMP_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD_DIRECTIVE";
  case 279: return "OMP_TARGET_TEAMS_DISTRIBUTE_SIMD_DIRECTIVE";
  case 280: return "BUILTIN_BIT_CAST_EXPR";
  case 281: return "OMP_MASTER_TASK_LOOP_DIRECTIVE";
  case 282: return "OMP_PARALLEL_MASTER_TASK_LOOP_DIRECTIVE";
  case 283: return "OMP_MASTER_TASK_LOOP_SIMD_DIRECTIVE";
  case 284: return "OMP_PARALLEL_MASTER_TASK_LOOP_SIMD_DIRECTIVE";
  case 285: return "OMP_PARALLEL_MASTER_DIRECTIVE";
  case 286: return "OMP_DEPOBJ_DIRECTIVE";
  case 287: return "OMP_SCAN_DIRECTIVE";
  case 288: return "OMP_TILE_DIRECTIVE";
  case 289: return "OMP_CANONICAL_LOOP";
  case 290: return "OMP_INTEROP_DIRECTIVE";
  case 291: return "OMP_DISPATCH_DIRECTIVE";
  case 292: return "OMP_MASKED_DIRECTIVE";
  case 293: return "OMP_UNROLL_DIRECTIVE";
  case 294: return "OMP_META_DIRECTIVE";
  case 295: return "OMP_GENERIC_LOOP_DIRECTIVE";
  case 296: return "OMP_TEAMS_GENERIC_LOOP_DIRECTIVE";
  case 297: return "OMP_TARGET_TEAMS_GENERIC_LOOP_DIRECTIVE";
  case 298: return "OMP_PARALLEL_GENERIC_LOOP_DIRECTIVE";
  case 299: return "OMP_TARGET_PARALLEL_GENERIC_LOOP_DIRECTIVE";
  case 300: return "OMP_PARALLEL_MASKED_DIRECTIVE";
  case 301: return "OMP_MASKED_TASK_LOOP_DIRECTIVE";
  case 302: return "OMP_MASKED_TASK_LOOP_SIMD_DIRECTIVE";
  case 303: return "OMP_PARALLEL_MASKED_TASK_LOOP_DIRECTIVE";
  case 304: return "OMP_PARALLEL_MASKED_TASK_LOOP_SIMD_DIRECTIVE";
  case 350: return "TRANSLATION_UNIT";
  case 400: return "UNEXPOSED_ATTR";
  case 401: return "IB_ACTION_ATTR";
  case 402: return "IB_OUTLET_ATTR";
  case 403: return "IB_OUTLET_COLLECTION_ATTR";
  case 404: return "CXX_FINAL_ATTR";
  case 405: return "CXX_OVERRIDE_ATTR";
  case 406: return "ANNOTATE_ATTR";
  case 407: return "ASM_LABEL_ATTR";
  case 408: return "PACKED_ATTR";
  case 409: return "PURE_ATTR";
  case 410: return "CONST_ATTR";
  case 411: return "NODUPLICATE_ATTR";
  case 412: return "CUDACONSTANT_ATTR";
  case 413: return "CUDADEVICE_ATTR";
  case 414: return "CUDAGLOBAL_ATTR";
  case 415: return "CUDAHOST_ATTR";
  case 416: return "CUDASHARED_ATTR";
  case 417: return "VISIBILITY_ATTR";
  case 418: return "DLLEXPORT_ATTR";
  case 419: return "DLLIMPORT_ATTR";
  case 438: return "CONVERGENT_ATTR";
  case 439: return "WARN_UNUSED_ATTR";
  case 440: return "WARN_UNUSED_RESULT_ATTR";
  case 441: return "ALIGNED_ATTR";
  case 500: return "PREPROCESSING_DIRECTIVE";
  case 501: return "MACRO_DEFINITION";
  case 502: return "MACRO_INSTANTIATION";
  case 503: return "INCLUSION_DIRECTIVE";
  case 600: return "MODULE_IMPORT_DECL";
  case 601: return "TYPE_ALIAS_TEMPLATE_DECL";
  case 602: return "STATIC_ASSERT";
  case 603: return "FRIEND_DECL";
  case 604: return "CONCEPT_DECL";
  case 700: return "OVERLOAD_CANDIDATE";
  default: {
    // Unknown kind -- cannot happen when both tools use the same libclang.
    // Return a loud marker rather than silently diverging from Python.
    static thread_local char buf[32];
    std::snprintf(buf, sizeof(buf), "<UNKNOWN_KIND_%u>", kind);
    return buf;
  }
  }
}

} // namespace cli
} // namespace cidx
