// kind_names.hpp — Python CursorKind.name lookup for the `cidx ast` commands.
//
// Maps CXCursorKind int values to the Python-registered name strings (e.g.
// "FUNCTION_DECL", not clang_getCursorKindSpelling's "FunctionDecl").  The
// table has irregularities that no mechanical transform can reproduce:
//   121 -> StmtExpr  (not STMT_EXPR)
//   251 -> OMP_PARALLELFORSIMD_DIRECTIVE
//   264 -> OMP_TARGET_PARALLELFOR_DIRECTIVE
// Generated by scripts/gen_kind_names.py from the pinned clang.cindex 18.1.1.
// DO NOT EDIT BY HAND — regenerate with: python scripts/gen_kind_names.py
#pragma once

#include <cstdio>

namespace cidx {
namespace cli {

// Returns the Python CursorKind.name for a CXCursorKind value, or a loud
// "<UNKNOWN_KIND_N>" marker for any value not present in the table.
const char *kind_name(unsigned kind);

} // namespace cli
} // namespace cidx
