"""cidx indexer package.

Modules:
    storage -- SQLite-backed symbol index (components / directories / files / symbols).
    query   -- low-level read-only graph-query API over the index (GraphQuery).
    model   -- high-level OO view over the symbol graph (CodeBase + typed entities).
    entity_graph -- OO reader over the Layer-1 entity_edge (design-entity) graph.
"""

from .storage import Storage, Component, Directory, File, Symbol, SYMBOL_KINDS
from .query import (
    CallerWithContext,
    GraphQuery,
    Sym,
    Edge,
    Site,
    Traversal,
    NoIndexError,
    NoEdgesError,
    open_query,
    default_db_path,
)
from .model import (
    CallerWithContextModel,
    CodeBase,
    open_codebase,
    Signature,
    Location,
    Type,
    Reference,
    Entity,
    Callable,
    Function,
    Method,
    Constructor,
    Destructor,
    Record,
    Class,
    Struct,
    Union,
    Field,
    Enum,
    EnumConstant,
    Typedef,
    Namespace,
    Variable,
    Macro,
    FunctionTemplate,
    ClassTemplate,
)
from .entity_graph import (
    EntityGraph,
    EntityNode,
    ClassNode,
    AbstractClassNode,
    InterfaceNode,
    UnionNode,
    EnumNode,
    ClassTemplateNode,
    AbstractClassTemplateNode,
    InterfaceTemplateNode,
    EntityEdge,
    EdgeKind,
    EntityKind,
    EntityType,
    Multiplicity,
    Access,
    CreateForm,
    open_entity_graph,
    ClassKind,
    Seed,
    Klass,
    AbstractClass,
    Struct as StructSeed,
    ClassTemplate as EntityClassTemplate,
    Instance,
    Interface,
)

__all__ = [
    "Storage",
    "Component",
    "Directory",
    "File",
    "Symbol",
    "SYMBOL_KINDS",
    "CallerWithContext",
    "CallerWithContextModel",
    "GraphQuery",
    "Sym",
    "Edge",
    "Site",
    "Traversal",
    "NoIndexError",
    "NoEdgesError",
    "open_query",
    "default_db_path",
    # high-level model layer
    "CodeBase",
    "open_codebase",
    "Signature",
    "Location",
    "Type",
    "Reference",
    "Entity",
    "Callable",
    "Function",
    "Method",
    "Constructor",
    "Destructor",
    "Record",
    "Class",
    "Struct",
    "Union",
    "Field",
    "Enum",
    "EnumConstant",
    "Typedef",
    "Namespace",
    "Variable",
    "Macro",
    "FunctionTemplate",
    "ClassTemplate",
    # Layer-1 entity-graph reader
    "EntityGraph",
    "EntityNode",
    "ClassNode",
    "AbstractClassNode",
    "InterfaceNode",
    "UnionNode",
    "EnumNode",
    "ClassTemplateNode",
    "AbstractClassTemplateNode",
    "InterfaceTemplateNode",
    "EntityEdge",
    "EdgeKind",
    "EntityKind",
    "EntityType",
    "Multiplicity",
    "Access",
    "CreateForm",
    "open_entity_graph",
    "ClassKind",
    # typed entity-query seeds (model-layer Record/Struct/ClassTemplate take the
    # bare names; the entity-graph seeds are re-exported with disambiguating
    # aliases -- StructSeed / EntityClassTemplate -- to avoid clashing).
    "Seed",
    "Klass",
    "AbstractClass",
    "StructSeed",
    "EntityClassTemplate",
    "Instance",
    "Interface",
]
